# Generated by Django 3.2.25 on 2024-07-23 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='workimages')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('appointed', models.ManyToManyField(related_name='appointed_works', to=settings.AUTH_USER_MODEL)),
                ('appointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointer_works', to=settings.AUTH_USER_MODEL)),
                ('relatedWork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.work')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.workstatus')),
            ],
        ),
    ]
