# Generated by Django 3.2.25 on 2024-07-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_work_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='indexName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
