# Generated by Django 3.2.25 on 2024-07-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_workreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstatus',
            name='indexName',
        ),
    ]
