# Generated by Django 3.2.25 on 2024-07-25 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_remove_workstatus_indexname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='workimages/wallpaperflare.com_wallpaper_a0D2PW1.jpg', null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='work',
            name='appointer',
            field=models.ForeignKey(default=task_app.models.deafult_appointer, on_delete=django.db.models.deletion.CASCADE, related_name='appointer_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.ForeignKey(default=task_app.models.default_work_status, on_delete=django.db.models.deletion.CASCADE, to='task_app.workstatus'),
        ),
    ]
