# Generated by Django 3.2.25 on 2024-07-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_auto_20240725_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
    ]
