# Generated by Django 3.2.25 on 2024-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_remove_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pictures\\profile.png', null=True, upload_to='profile_pictures'),
        ),
    ]
