# Generated by Django 3.2.25 on 2024-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
