# Generated by Django 3.2.25 on 2024-08-01 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_work_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='status',
            field=models.ForeignKey(default=task_app.models.default_work_status, on_delete=django.db.models.deletion.CASCADE, to='task_app.workstatus'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='writer',
            field=models.ForeignKey(default=task_app.models.deafult_appointer, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
