# Generated by Django 3.2.25 on 2024-08-05 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_auto_20240801_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRevise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='workimages')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointed_revise', to=settings.AUTH_USER_MODEL)),
                ('appointer', models.ForeignKey(default=task_app.models.deafult_appointer, on_delete=django.db.models.deletion.CASCADE, related_name='appointer_revise', to=settings.AUTH_USER_MODEL)),
                ('relatedWork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.work')),
                ('status', models.ForeignKey(default=task_app.models.default_work_status, on_delete=django.db.models.deletion.CASCADE, to='task_app.workstatus')),
            ],
        ),
    ]
