# Generated by Django 3.2.25 on 2024-08-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_workrevise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrevise',
            name='relatedWork',
        ),
        migrations.AddField(
            model_name='workrevise',
            name='relatedReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.workreport'),
        ),
    ]
