# Generated by Django 3.2.25 on 2024-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_remove_workrevise_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
